[package]
name = "pkger-core"
version = "0.7.0"
edition = "2021"
authors = ["Wojciech KÄ™pka <wojciech@wkepka.dev>"]
license = "MIT"

[dependencies]
deb-control = { path = "../libs/debcontrol" }
rpmspec = { path = "../libs/rpmspec" }
pkgbuild = { path = "../libs/pkgbuild" }
apkbuild = { path = "../libs/apkbuild" }

docker-api = { git = "https://github.com/vv9k/docker-api-rs" }

anyhow = "1"

tar = "0.4"
flate2 = "1"

tracing = "0.1"

async-rwlock = "1"
futures = "0.3"

serde = {version = "1.0", features = ["derive"]}
serde_cbor = "0.11"
serde_yaml = "0.8"

tempdir = "0.3"

uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
pretty_assertions = "0.3"
